[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"


[tool.mypy]
python_version = "3.11"
namespace_packages = true


[[tool.mypy.overrides]]
module = [
    "setuptools",
]
ignore_missing_imports = true
